name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x" # Try a different Go version

      - name: Run tests
        run: go test -cover ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: ~/go/bin/gosec ./...

      
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"

      - name: Check formatting
        run: test -z "$(go fmt ./...)"

      - name: List files
        run: ls -R
        working-directory: ${{ github.workspace }}

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
        working-directory: ${{ github.workspace }}

      - name: Run staticcheck
        run: ~/go/bin/staticcheck ./...
        working-directory: ${{ github.workspace }}